repos:
-   repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    -   id: black
        additional_dependencies: ['click==8.0.4']
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
    -   id: mypy
        args: ['--show-error-codes', '--check-untyped-defs', '--follow-imports=silent', '--ignore-missing-imports', '--warn-redundant-casts', '--strict-equality', '--warn-unused-ignores', '--warn-return-any', '--disallow-incomplete-defs']
-   repo: https://github.com/pycqa/isort
    rev: 5.6.4
    hooks:
        - id: isort
          args: ["--profile", "black", "--filter-files"]
